export const ERRORS = {
  ERROR_1: "Something went wrong!",
  ERROR_2: "An unknown error occurred.",
  ERROR_3: "An unknown error occurred, Please try again.",
  ERROR_4: "Error occurred while getting display names.",
  ERROR_5: "Please fill required details.",
};

export const WATCH_CATEGORIES = [
  "Space timer jupiter",
  "Breitling Galactic",
  "Opus chronograph",
  "Cali diver",
  "Ceramics",
  "Pilot's watch",
  "Luxury dress",
  "Divers",
  "Field watch",
  "Smartwatch",
  "Skeleton",
  "Chronograph",
  "Minimalist",
  "Vintage",
  "Sports watch",
  "Tactical",
  "Automatic",
  "Moonphase",
  "Luxury sport",
  "Digital",
  "Swiss made",
  "Smart hybrid",
  "GMT",
];

export const WATCH_BRANDS = [
  "Rolex",
  "Omega",
  "Tag Heuer",
  "Patek Philippe",
  "Audemars Piguet",
  "Seiko",
  "Casio",
  "Breitling",
  "Panerai",
  "Hublot",
  "Tudor",
  "Longines",
  "Citizen",
  "IWC",
  "Fossil",
  "Hamilton",
  "Bvlgari",
  "Girard-Perregaux",
  "Jaeger-LeCoultre",
  "Vacheron Constantin",
  "Breguet",
];

export const WATCH_STRAPS = [
  "Leather",
  "Rubber",
  "Stainless Steel",
  "NATO",
  "Mesh",
  "Silicone",
  "Canvas",
  "Velcro",
  "Ceramic",
  "Alligator",
  "Lizard",
  "Textile",
  "Cordura",
  "Genuine Leather",
];

export const WATCH_BUCKLES = [
  "Pin Buckle",
  "Deployant Buckle",
  "Butterfly Clasp",
  "Tang Buckle",
  "Fold-over Clasp",
  "Double Push-Button Clasp",
  "Diver Clasp",
  "Deployant Clasp",
  "Hook-and-Loop (Velcro)",
  "Magnetic Clasp",
  "Push-button Butterfly",
  "Folding Buckle",
];

export const WATCH_STRAP_SIZES = [
  "16mm",
  "18mm",
  "20mm",
  "22mm",
  "24mm",
  "26mm",
  "28mm",
  "30mm",
  "32mm",
];


export const WATCH_MOVEMENTS = [
  "Automatic",
  "Manual Wind",
  "Quartz",
  "Hybrid Movement",
  "Solar Powered",
  "Kinetic",
  "Tourbillon",
  "Chronograph",
  "GMT",
  "Smart Movement",
  "Skeletonized",
];

export const WATER_RESISTANCE = [
  "30 meters",
  "50 meters",
  "100 meters",
  "200 meters",
  "300 meters",
  "500 meters",
  "1000 meters",
  "1500 meters",
  "3000 meters",
  "Diver's Watch (ISO 6425 Certified)",
  "Splash Resistant",
  "Water-Resistant (Non-Diver)",
];

export const CASE_MATERIALS = [
  "Stainless Steel",
  "Titanium",
  "Ceramic",
  "Gold (18k, 14k)",
  "Platinum",
  "Carbon Fiber",
  "Aluminum",
  "Bronze",
  "PVD Coated Steel",
  "Rose Gold",
  "White Gold",
  "Ceramic Coated Titanium",
  "Stainless Steel with PVD Coating",
];

export const CASE_DIAMETERS = [
  "36mm",
  "38mm",
  "40mm",
  "42mm",
  "44mm",
  "46mm",
  "48mm",
  "50mm",
  "52mm",
  "55mm",
];

export const DIAL_COLORS = [
  "Black",
  "White",
  "Blue",
  "Silver",
  "Gray",
  "Green",
  "Brown",
  "Red",
  "Orange",
  "Yellow",
  "Gold",
];
