export const PRODUCT_CATEGORIES = [
  "HEADPHONES",
  "EARBUDS",
  "SPEAKERS",
  "MICROPHONES",
  "AMPLIFIERS",
  "SOUNDBARS",
  "ACCESSORIES",
  "CABLES_ADAPTERS",
  "AUDIO_INTERFACES",
  "HOME_THEATER",
];
